--[[

LUA Script generated by PLUMGEN

--]]

--## BFN Biome + Weights ##----------------------------------------------------
local addHeader =
[[
  <Property name="BiomeFiles">
  </Property>
]]

function addPlanetType(planetType)
return [[
    <Property name="]] .. planetType .. [[" value="GcBiomeFileListOptions.xml">
      <Property name="FileOptions">
      </Property>
    </Property>
]]
end

function addFileListOption(subType, filename, weight) --NEED proper subtype
return [[
        <Property value="GcBiomeFileListOption.xml">
          <Property name="SubType" value="GcBiomeSubType.xml">
            <Property name="BiomeSubType" value="]] .. subType .. [[" />
          </Property>
          <Property name="Filename" value="]] .. filename .. [[" />
          <Property name="Weight" value="]] .. weight .. [[" />
        </Property>
]]
end

--## BFN Valid Start Planets ##-----------------------------------------------
local addStartHeader =
[[
  <Property name="ValidStartPlanetBiome">
  </Property>
]]


function addStartBody(biomeType)
return [[
    <Property value="GcBiomeType.xml">
      <Property name="Biome" value="]] .. biomeType .. [[" />
    </Property>
]]
end

--## BFN Tiletypes ##---------------------------------------------------------
local addCommonExternalHeader = 
[[
  <Property name="CommonExternalObjectLists">
  </Property>
]]

function addCommonExternalBody(weight, tileType)
return [[
    <Property value="GcExternalObjectListOptions.xml">
      <Property name="Name" value="PLUMGEN_STUFF" />
      <Property name="ResourceHint" value="" />
      <Property name="ResourceHintIcon" value="" />
      <Property name="Probability" value="]] .. weight .. [[" />
      <Property name="SeasonalProbabilityOverride" value="1" />
      <Property name="TileType" value="GcTerrainTileType.xml">
        <Property name="TileType" value="]] .. tileType .. [[" />
      </Property>
      <Property name="AllowLimiting" value="False" />
      <Property name="ChooseUsingLifeLevel" value="False" />
      <Property name="Options">
      </Property>
    </Property>
]]
end

function addBiomeOptions(biomeObjectsName)
return [[
        <Property value="NMSString0x80.xml">
          <Property name="Value" value="]] .. biomeObjectsName .. [[" />
        </Property>
]]
end

--##Each biome file ##------------------------------------------------------
local addEachBiomeHeader =
[[
  <Property name="ExternalObjectLists">
  </Property>
]]

--Reuses above 2 functions




NMS_MOD_DEFINITION_CONTAINER = 
{
--["AMUMSS_SUPPRESS_MSG"] = "UNUSED_VARIABLE", --remove notices that a variable was not used
["MOD_FILENAME"] 			= "@mod_title@.pak",
["MOD_AUTHOR"]				= "@mod_author@",
["NMS_VERSION"]				= "",
["MODIFICATIONS"] 			= 
	{
		{
			["PAK_FILE_SOURCE"] 	= "NMSARC.515F1D3.pak",
			["MBIN_CHANGE_TABLE"] 	= 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= 
					{
						"METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BIOMEFILENAMES.MBIN"
					},
					["EXML_CHANGE_TABLE"] 	= 
					{
						--### BiomeFilles + Weights ### ----------------------------------
						{
							["PRECEDING_KEY_WORDS"] = { "BiomeFiles", },
							["ADD_OPTION"] 	= "ADDafterSECTION",
							["ADD"] = addHeader,
						},
						{
							["PRECEDING_KEY_WORDS"] = {"BiomeFiles",},
							["REMOVE"] = "SECTION",
						},
						--For each planet type, i.e. Lush
						{
							["PRECEDING_KEY_WORDS"] = { "BiomeFiles", },
							["ADD_OPTION"] 	= "ADDafterLINE",
							["ADD"] = addPlanetType(@planetType@),
						},
						--For each filename + weight
						{
							["PRECEDING_KEY_WORDS"] = { "FileOptions", },
							["ADD_OPTION"] 	= "ADDafterLINE",
							["ADD"] = addFileListOption(@subType, filename, weight@), --subBiomeType
						},
						
						
						--### ValidStartPlanet ### ---------------------------------------
						{
							["PRECEDING_KEY_WORDS"] = { "ValidStartPlanetBiome", },
							["ADD_OPTION"] 	= "ADDafterSECTION",
							["ADD"] = addStartHeader,
						},
						{
							["PRECEDING_KEY_WORDS"] = {"ValidStartPlanetBiome",},
							["REMOVE"] = "SECTION",
						},
						--Add 1 for each valid start planet
						{
							["PRECEDING_KEY_WORDS"] = { "ValidStartPlanetBiome", },
							["ADD_OPTION"] 	= "ADDafterLINE",
							["ADD"] = addStartBody(@biomeType@),
						},
						
						
						--### CommonExternalObjects ### ----------------------------------
						{
							["PRECEDING_KEY_WORDS"] = { "CommonExternalObjectLists", },
							["ADD_OPTION"] 	= "ADDafterSECTION",
							["ADD"] = addCommonExternalHeader,
						},
						{
							["PRECEDING_KEY_WORDS"] = {"CommonExternalObjectLists",},
							["REMOVE"] = "SECTION",
						},
						
						--Each tiletype
						{
							["PRECEDING_KEY_WORDS"] = { "CommonExternalObjectLists", },
							["ADD_OPTION"] 	= "ADDafterLINE",
							["ADD"] = addCommonExternalBody(@weight@, @tile_type@),
						},
						
						--For each tiletype, add multiple:
						{
							["PRECEDING_KEY_WORDS"] = { "Options", },
							["ADD_OPTION"] 	= "ADDafterLINE",
							["ADD"] = addBiomeOptions(@biomeObjectsName@),
						},
						
					}
				},
				
				{
					["MBIN_FILE_SOURCE"] 	= "@each_biome_mbin@",
					["EXML_CHANGE_TABLE"] 	= 
					{
						{
							["PRECEDING_KEY_WORDS"] = { "ExternalObjectLists", },
							["ADD_OPTION"] 	= "ADDafterSECTION",
							["ADD"] = addEachBiomeHeader,
						},
						{
							["PRECEDING_KEY_WORDS"] = {"ExternalObjectLists",},
							["REMOVE"] = "SECTION",
						},
						
						--Each biome tiletype
						{
							["PRECEDING_KEY_WORDS"] = { "ExternalObjectLists", },
							["ADD_OPTION"] 	= "ADDafterLINE",
							["ADD"] = addCommonExternalBody(@weight@, @tile_type@),
						},
						
						--For each biome tiletype, add multiple:
						{
							["PRECEDING_KEY_WORDS"] = { "Options", },
							["ADD_OPTION"] 	= "ADDafterLINE",
							["ADD"] = addBiomeOptions(@biomeObjectsName@),
						},
						
					}
				},
				
			}
		},
    }
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PAST THIS POINT HERE